/**
 * App-wide copy strings. Kept in const-values per CLAUDE.md so components
 * stay strictly presentational.
 */

export const APP_COPY = {
	taskListTitle: 'Tasks',
	taskListEmpty: 'No tasks yet — drop something via Discord, Telegram, or the voice agent.',
	taskListAllDoneHidden: 'All tasks complete (hidden). Toggle "show done" to reveal.',
	taskShowDetails: 'Show details ▸',
	taskHideDetails: 'Hide ▾',
	taskShowDone: 'show done',
	taskHideDone: 'hide done',
	taskCollapseAll: 'collapse all',
	taskExpandAll: 'expand all',
	taskSystemBrainOffline: 'brain offline',
	taskSystemWatcherOffline: 'watcher offline',
	taskReplyPlaceholder: 'Type a reply…',
	taskReplyPlaceholderOrType: 'or type a reply…',
	taskReplySend: 'Send',
	taskReplySending: 'Sending…',
	taskReplySent: 'Replied:',
	taskReplyFailed: 'Reply failed —',
	questionsTitle: 'Pending questions',
	questionPlaceholder: 'Or type a response…',
	questionSend: 'Send',
	questionSending: 'Sending…',
	questionAnswered: 'Answered:',
	questionFailed: 'Answer failed —',

	convGreeting: 'Hey, I’m Sutando.',
	convTagline: 'Your AI partner — voice or text, hands-free or hands-on.',
	convStartVoice: 'Start voice',
	convConnecting: 'Connecting…',
	convStatusTextOnly: 'Text only',
	convStatusVoiceLive: 'Voice live',
	convStatusConnecting: 'Connecting',
	convStatusError: 'Voice error',
	convPanelTasks: 'Tasks',
	convPanelNotes: 'Notes',
	convPanelQuestions: 'Asks',
	convPanelActivity: 'Activity',
	convPanelDrawerClose: 'Close panel',
	convComposerPlaceholder: 'Ask Sutando anything…',
	convComposerSend: 'Send',
	convDashboardLink: 'Dashboard',
	convMute: 'Mute',
	convUnmute: 'Unmute',
	convEnd: 'End',
	convWatch: '👁️ Watch',
	convWatching: '👁️ Watching',
	convStreamEmpty: 'No messages yet. Try a quick start or speak with the orb.',
} as const;
